# -*- coding: utf-8 -*-
"""
Sphinx configuration file for zen documentation.

"""
## ===========================================================================
# environment setup
## ===========================================================================
import os
import sys

# make sure root of source dir in sys.path
sys.path.insert(0, os.path.abspath(os.pardir))

# # read env var for tags, needed since "python setup.py build_sphinx"
# # doesn't support sphinx-build's "-t" option.
# for _tag in os.environ.get("SPHINX_BUILD_TAGS", "").split():
    # tags.add(_tag)

#=============================================================================
# General configuration
#=============================================================================

## -- extensions -------------------------------------------------------------
_exts = "../exts"
sys.path.append(os.path.abspath(_exts))

extensions = [    
    # standard sphinx extensions
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinx.ext.autosectionlabel', # Auto-generate section labels.
    'sphinx.ext.mathjax', #math support 
    
    # 3rd party extensions
    'sphinxcontrib.fulltoc',
    'sphinx.ext.viewcode',  # mainly to make sure layout works properly
    'chinese_search', # self defined 
    
    # cloud's extensions
    'cloud_sptheme.ext.autodoc_sections',
    'cloud_sptheme.ext.relbar_links',
    'cloud_sptheme.ext.escaped_samp_literals',
    'cloud_sptheme.ext.issue_tracker',
    'cloud_sptheme.ext.table_styling',
    'cloud_sptheme.ext.role_index',  # NOTE: used only to provide example role index

    # 'recommonmark',
    # 'sphinx_markdown_tables',
    # 'sphinxemoji.sphinxemoji',
    # 'sphinx.ext.autodoc',
    # 'sphinx.ext.doctest',
    # 'sphinx.ext.intersphinx',
    # 'sphinx.ext.coverage',
    # 'sphinx.ext.ifconfig',
    # 'sphinx.ext.githubpages',
]

# section labels numbered
autosectionlabel_prefix_document = True

## -- config ---------------------------------------------------------------------
# Add any paths that contain templates here, relative to this directory.
templates_path = ['./_templates']

# The suffix of source filenames.
source_suffix = '.rst' 
# source_suffix = ['.rst','.md']

# The encoding of source files.
source_encoding = 'utf-8'

# The master toctree document. ??
master_doc = 'toc'

# The frontpage document. name of index doc
index_doc = 'index'

# If true, '()' will be appended to :func: etc. cross-reference text.
add_function_parentheses = True

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    #"lib/cloud_sptheme.make_helper.rst", 
]

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
##add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
##show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
modindex_common_prefix = [ "cloud_sptheme." ]

# -- Project information -----------------------------------------------------

project = 'Zen'
author = 'Adam Zhou'
copyright = "2020, "+ author

# The full version, including alpha/beta/rc tags
release = '1.1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = "zh_CN"
language = None
# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
today = ''


#=============================================================================
# Options for all output
#=============================================================================
todo_include_todos = True
keep_warnings = False
issue_tracker_url = "https://github.com/AdamZhou3/Zen_Doc/issues/{issue}"

#=============================================================================
# Options for HTML output
#=============================================================================
import cloud_sptheme as csp
# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes. redcloud greencloud 
html_theme = 'magenta_cloud'
#html_theme = 'cloud'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {}
if csp.is_cloud_theme(html_theme):
    html_theme_options.update(
        roottarget=index_doc,
        borderless_decor=True,
        max_width="13in",##11in default
        default_layout_text_size="75.5%",#87.5% 
        #shaded_decor=False,
        sidebarwidth="2.5in",
        hyphenation_language="en",
    )
# https://cloud-sptheme.readthedocs.io/en/latest/cloud_theme.html

# Add any paths that contain custom themes here, relative to this directory.
if csp.is_cloud_theme(html_theme):
    # so build works even if package isn't installed
    html_theme_path = [csp._theme_dir] # envs/doc/lib/site-packages/cloud_sptheme/themes'


# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = "%s v%s" % (project, release)

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = "%s %s Documentation" % (project, version) # version no defined 

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = os.path.join("./_static", "logo.PNG")

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
##html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['./_static']
html_js_files = [
    'js/baidutongji.js', 
]

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
##html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
html_sidebars = {
    '**': ['searchbox.html', 
        'globaltoc.html',
        #'localtoc.html'
        ]}

# Additional templates that should be rendered to pages, maps page names to
# template names.
##html_additional_pages = {}

# If false, no module index is generated.
##html_domain_indices = True

# If false, no index is generated.
##html_use_index = True

# If true, the index is split into individual pages for each letter.
##html_split_index = False

# If true, links to the reST sources are added to the pages.
##html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
##html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
##html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
##html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = project + 'Doc'


#=============================================================================
# Options for LaTex output
#=============================================================================
latex_elements = {  # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'a4paper',  # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '12pt', 'classoptions': ',oneside', 'babel': '',  # 必须
    'inputenc': '',  # 必须
    'utf8extra': '',  # 必须
    # Additional stuff for the LaTeX preamble.
    'preamble': r"""
\usepackage{xeCJK}
\usepackage{indentfirst}
\setlength{\parindent}{2em}
\setCJKmainfont{WenQuanYi Micro Hei}
\setCJKmonofont[Scale=0.9]{WenQuanYi Micro Hei Mono}
\setCJKfamilyfont{song}{WenQuanYi Micro Hei}
\setCJKfamilyfont{sf}{WenQuanYi Micro Hei}
\XeTeXlinebreaklocale "zh"
\XeTeXlinebreakskip = 0pt plus 1pt
      """}
      
# The paper size ('letter' or 'a4').
##latex_paper_size = 'letter'

# The font size ('10pt', '11pt' or '12pt').
##latex_font_size = '10pt'

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
  (index_doc, project + '.tex', project + ' Documentation',
   author, 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
##latex_use_parts = False

# If true, show page references after internal links.
##latex_show_pagerefs = False

# If true, show URL addresses after external links.
##latex_show_urls = False

# Additional stuff for the LaTeX preamble.
##latex_preamble = ''

# Documents to append as an appendix to all manuals.
##latex_appendices = []

# If false, no module index is generated.
##latex_domain_indices = True


#=============================================================================
# EOF
#=============================================================================
